package es.elultimorey.forocoches;

public enum EnumShortcut {
	DEFECTO_FIRST, DEFECTO_SECOND, PANEL_U, MENCIONES, PRIVADOS, TEMAS_S, TEMAS_S_N, PANEL_H, RESPONDER, NUEVO_TEMA, BUSCAR, COMPARTIR, ADELANTE, ATRAS
}
